# Generated by Django 5.2.5 on 2025-08-12 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(unique=True)),
                ('name_ar', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_surah', models.PositiveSmallIntegerField()),
                ('text_ar', models.TextField()),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.surah')),
            ],
            options={
                'unique_together': {('surah', 'number_in_surah')},
            },
        ),
    ]
