# Generated by Django 5.2.5 on 2025-08-13 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_ar', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ayah',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Lexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_ar', models.CharField(max_length=64)),
                ('translit', models.CharField(blank=True, max_length=64)),
                ('pos', models.CharField(blank=True, max_length=32)),
                ('gloss', models.CharField(blank=True, max_length=128)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.root')),
            ],
            options={
                'unique_together': {('root', 'form_ar')},
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayah_no', models.PositiveSmallIntegerField()),
                ('token_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lexeme')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.surah')),
            ],
            options={
                'indexes': [models.Index(fields=['surah', 'ayah_no'], name='core_occurr_surah_i_5b03a6_idx')],
            },
        ),
    ]
