# Generated by Django 5.2.5 on 2025-08-15 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_root_alter_ayah_unique_together_lexeme_occurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TopicVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayah_no', models.PositiveSmallIntegerField()),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.surah')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.topic')),
            ],
            options={
                'indexes': [models.Index(fields=['surah', 'ayah_no'], name='core_topicv_surah_i_820c56_idx')],
                'unique_together': {('topic', 'surah', 'ayah_no')},
            },
        ),
    ]
