# Generated by Django 5.2.5 on 2025-08-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_topic_topicverse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayah',
            options={'ordering': ('surah__index', 'number_in_surah')},
        ),
        migrations.AlterModelOptions(
            name='lexeme',
            options={'ordering': ('form_ar',)},
        ),
        migrations.AlterModelOptions(
            name='occurrence',
            options={'ordering': ('surah__index', 'ayah_no')},
        ),
        migrations.AlterModelOptions(
            name='surah',
            options={'ordering': ('index',)},
        ),
        migrations.AlterModelOptions(
            name='topicverse',
            options={'ordering': ('surah__index', 'ayah_no')},
        ),
        migrations.AddField(
            model_name='surah',
            name='ayat_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surah',
            name='name_uz',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='surah',
            name='nuzul_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surah',
            name='nuzul_place',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='surah',
            name='name_ar',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='ayah',
            unique_together={('surah', 'number_in_surah')},
        ),
    ]
