# core/constants.py
ARABIC_LETTERS = [
    "ا","ب","ت","ث","ج","ح","خ","د","ذ","ر","ز","س","ش",
    "ص","ض","ط","ظ","ع","غ","ف","ق","ك","ل","م","ن","ه","و","ي"
]
# Asma'ul Husna — Allohning 99 ismlari va qisqa ma'nolari (UZ)
ASMA_UL_HUSNA = [
    {"name_ar": "ٱللّٰه", "meaning_uz": "Alloh (Yagonadir)"},
    {"name_ar": "ٱلرَّحْمَٰن", "meaning_uz": "Cheksiz Mehribon"},
    {"name_ar": "ٱلرَّحِيم", "meaning_uz": "Beqiyos Rahmli"},
    {"name_ar": "ٱلْمَلِك", "meaning_uz": "Podshoh, Hukmron"},
    {"name_ar": "ٱلْقُدُّوس", "meaning_uz": "Mutlaq Pok"},
    {"name_ar": "ٱلسَّلَام", "meaning_uz": "Salomatlik manbai"},
    {"name_ar": "ٱلْمُؤْمِن", "meaning_uz": "Omonga chiqaruvchi"},
    {"name_ar": "ٱلْمُهَيْمِن", "meaning_uz": "Qo‘riqlovchi, Nazoratchi"},
    {"name_ar": "ٱلْعَزِيز", "meaning_uz": "Qudratli, G‘olib"},
    {"name_ar": "ٱلْجَبَّار", "meaning_uz": "Jabr qiluvchi, Tuzatuvchi"},
    {"name_ar": "ٱلْمُتَكَبِّر", "meaning_uz": "Buyuklik sohibi"},
    {"name_ar": "ٱلْخَالِق", "meaning_uz": "Yaratgan"},
    {"name_ar": "ٱلْبَارِئ", "meaning_uz": "Yo‘qdan bor qiluvchi"},
    {"name_ar": "ٱلْمُصَوِّر", "meaning_uz": "Suralar beruvchi"},
    {"name_ar": "ٱلْغَفَّار", "meaning_uz": "Ko‘p mag‘firat qiluvchi"},
    {"name_ar": "ٱلْقَهَّار", "meaning_uz": "Zabardast g‘olib"},
    {"name_ar": "ٱلْوَهَّاب", "meaning_uz": "Behisob ato qiluvchi"},
    {"name_ar": "ٱلرَّزَّاق", "meaning_uz": "Rizq beruvchi"},
    {"name_ar": "ٱلْفَتَّاح", "meaning_uz": "Fath etuvchi, Ochuvchi"},
    {"name_ar": "ٱلْعَلِيم", "meaning_uz": "Biluvchi, Ilm sohibi"},
    {"name_ar": "ٱلْقَابِض", "meaning_uz": "Qisuvchi"},
    {"name_ar": "ٱلْبَاسِط", "meaning_uz": "Yoyuvchi, Kengaytiruvchi"},
    {"name_ar": "ٱلْخَافِض", "meaning_uz": "Past qiluvchi"},
    {"name_ar": "ٱلرَّافِع", "meaning_uz": "Ko‘taruvchi"},
    {"name_ar": "ٱلْمُعِزّ", "meaning_uz": "Izzat beruvchi"},
    {"name_ar": "ٱلْمُذِلّ", "meaning_uz": "Zillat beruvchi"},
    {"name_ar": "ٱلسَّمِيع", "meaning_uz": "Eshituvchi"},
    {"name_ar": "ٱلْبَصِير", "meaning_uz": "Ko‘ruvchi"},
    {"name_ar": "ٱلْحَكَم", "meaning_uz": "Hakam"},
    {"name_ar": "ٱلْعَدْل", "meaning_uz": "Adolatli"},
    {"name_ar": "ٱللَّطِيف", "meaning_uz": "Lutf-ehson qiluvchi"},
    {"name_ar": "ٱلْخَبِير", "meaning_uz": "Xabardor"},
    {"name_ar": "ٱلْحَلِيم", "meaning_uz": "Halim, Sabrli"},
    {"name_ar": "ٱلْعَظِيم", "meaning_uz": "Buyuk"},
    {"name_ar": "ٱلْغَفُور", "meaning_uz": "Ko‘p kechiruvchi"},
    {"name_ar": "ٱلشَّكُور", "meaning_uz": "Shukrni mukofotlovchi"},
    {"name_ar": "ٱلْعَلِيّ", "meaning_uz": "Yuqori, Oliy"},
    {"name_ar": "ٱلْكَبِير", "meaning_uz": "Ulug‘"},
    {"name_ar": "ٱلْحَفِيظ", "meaning_uz": "Saqlovchi"},
    {"name_ar": "ٱلْمُقِيت", "meaning_uz": "Ta’minlovchi"},
    {"name_ar": "ٱلْحَسِيب", "meaning_uz": "Hisob-kitob qiluvchi"},
    {"name_ar": "ٱلْجَلِيل", "meaning_uz": "Jalol egasi"},
    {"name_ar": "ٱلْكَرِيم", "meaning_uz": "Saxiy, Karim"},
    {"name_ar": "ٱلرَّقِيب", "meaning_uz": "Kuzatuvchi"},
    {"name_ar": "ٱلْمُجِيب", "meaning_uz": "Ijobat qiluvchi"},
    {"name_ar": "ٱلْوَاسِع", "meaning_uz": "Keng, Vasi‘"},
    {"name_ar": "ٱلْحَكِيم", "meaning_uz": "Hikmat sohibi"},
    {"name_ar": "ٱلْوَدُود", "meaning_uz": "Mehribon, Sevuvchi"},
    {"name_ar": "ٱلْمَجِيد", "meaning_uz": "Sharafli, Majid"},
    {"name_ar": "ٱلْبَاعِث", "meaning_uz": "Tiriltiruvchi"},
    {"name_ar": "ٱلشَّهِيد", "meaning_uz": "Guvoh"},
    {"name_ar": "ٱلْحَقّ", "meaning_uz": "Haq"},
    {"name_ar": "ٱلْوَكِيل", "meaning_uz": "Vekil"},
    {"name_ar": "ٱلْقَوِيّ", "meaning_uz": "Kuchli"},
    {"name_ar": "ٱلْمَتِين", "meaning_uz": "Mustahkam"},
    {"name_ar": "ٱلْوَلِيّ", "meaning_uz": "Do‘st, Homiy"},
    {"name_ar": "ٱلْحَمِيد", "meaning_uz": "Hamdu sano sohibi"},
    {"name_ar": "ٱلْمُحْصِي", "meaning_uz": "Sanovchi"},
    {"name_ar": "ٱلْمُبْدِئ", "meaning_uz": "Boshlovchi"},
    {"name_ar": "ٱلْمُعِيد", "meaning_uz": "Qaytaruvchi"},
    {"name_ar": "ٱلْمُحْيِي", "meaning_uz": "Hayot beruvchi"},
    {"name_ar": "ٱلْمُمِيت", "meaning_uz": "O‘lim beruvchi"},
    {"name_ar": "ٱلْحَيّ", "meaning_uz": "Tirik"},
    {"name_ar": "ٱلْقَيُّوم", "meaning_uz": "Qayyum"},
    {"name_ar": "ٱلْوَاجِد", "meaning_uz": "Topuvchi, Boy"},
    {"name_ar": "ٱلْوَاحِد", "meaning_uz": "Yakka, Yagona"},
    {"name_ar": "ٱلْأَحَد", "meaning_uz": "Mutlaq Yagona"},
    {"name_ar": "ٱلصَّمَد", "meaning_uz": "Hammasi Unga muhtoj"},
    {"name_ar": "ٱلْقَادِر", "meaning_uz": "Qodir"},
    {"name_ar": "ٱلْمُقْتَدِر", "meaning_uz": "Qudrat sohibi"},
    {"name_ar": "ٱلْمُقَدِّم", "meaning_uz": "Oldinga suruvchi"},
    {"name_ar": "ٱلْمُؤَخِّر", "meaning_uz": "Kechiktiruvchi"},
    {"name_ar": "ٱلْأَوَّل", "meaning_uz": "Birinchi"},
    {"name_ar": "ٱلْآخِر", "meaning_uz": "Oxirgi"},
    {"name_ar": "ٱلظَّاهِر", "meaning_uz": "Zohir"},
    {"name_ar": "ٱلْبَاطِن", "meaning_uz": "Botin"},
    {"name_ar": "ٱلْوَالِي", "meaning_uz": "Boshqaruvchi"},
    {"name_ar": "ٱلْمُتَعَالِي", "meaning_uz": "Yuksak, Ulug‘"},
    {"name_ar": "ٱلْبَرّ", "meaning_uz": "Yaxshilik qiluvchi"},
    {"name_ar": "ٱلتَّوَّاب", "meaning_uz": "Tavbani qabul qiluvchi"},
    {"name_ar": "ٱلْمُنْتَقِم", "meaning_uz": "Qasos oluvchi"},
    {"name_ar": "ٱلْعَفُوّ", "meaning_uz": "Afu qiluvchi"},
    {"name_ar": "ٱلرَّؤُوف", "meaning_uz": "Juda rahmli"},
    {"name_ar": "مَالِكُ ٱلْمُلْك", "meaning_uz": "Mulk egasi"},
    {"name_ar": "ذُو ٱلْجَلَالِ وَٱلْإِكْرَام", "meaning_uz": "Jalol va Ikrom egasi"},
    {"name_ar": "ٱلْمُقْسِط", "meaning_uz": "Adolat bilan bo‘luvchi"},
    {"name_ar": "ٱلْجَامِع", "meaning_uz": "Jamlovchi"},
    {"name_ar": "ٱلْغَنِيّ", "meaning_uz": "Behojat, Boy"},
    {"name_ar": "ٱلْمُغْنِي", "meaning_uz": "Boy qiluvchi"},
    {"name_ar": "ٱلْمَانِع", "meaning_uz": "To‘suvchi"},
    {"name_ar": "ٱلضَّارّ", "meaning_uz": "Ziyon yetkazuvchi"},
    {"name_ar": "ٱلنَّافِع", "meaning_uz": "Foyda beruvchi"},
    {"name_ar": "ٱلنُّور", "meaning_uz": "Nur"},
    {"name_ar": "ٱلْهَادِي", "meaning_uz": "Hidoyat qiluvchi"},
    {"name_ar": "ٱلْبَدِيع", "meaning_uz": "Be misol yaratuvchi"},
    {"name_ar": "ٱلْبَاقِي", "meaning_uz": "Abadiy qoluvchi"},
    {"name_ar": "ٱلْوَارِث", "meaning_uz": "Merosxo‘r"},
    {"name_ar": "ٱلرَّشِيد", "meaning_uz": "To‘g‘ri yo‘l ko‘rsatuvchi"},
    {"name_ar": "ٱلصَّبُور", "meaning_uz": "Juda sabrli"},
]